/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CronExpression;

public class App {

    public static void main(String[] args) {
        System.out.println(CronExpDescriptor.getFullDescription(args[0]));
    }
}
