/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CronExpression;

import org.checkerframework.checker.units.qual.C;

public class App {

    public static void main(String[] args) {
        CronExpDescriptor cronExpDescriptor= new CronExpDescriptor();
        System.out.println(cronExpDescriptor.getFullDescription(args[0]));
    }
}
