/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cronExpression;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
